M48
; DRILL file {KiCad 6.0.2+dfsg-1} date mer. 22 mars 2023 09:54:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-22T09:54:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
%
G90
G05
T1
X133.435Y-53.58
X133.435Y-58.18
X133.604Y-103.32
X133.604Y-107.92
T0
M30
